templates/pydbapp/pydb/urls.py
from django.contrib import admin
from django.urls import path, include

# from django.views.generic import RedirectView

urlpatterns = [
    path("pydbapp/", include("pydbapp.urls")),
    # path("", RedirectView.as_view(url="pydbapp/", permanent=True)),
    path("admin/", admin.site.urls),
]

urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "pydbapp"
urlpatterns = [
    path("search_products", views.search_products, name="search_products"),
    path("home", views.home, name="home"),
    path("", views.IndexView.as_view(), name="index"),
    path("product/search/<int:pk>/", views.search_product, name="search-product"),
    path("products/", views.ProductHomeView.as_view(), name="products"),
    path("vendors/", views.VendorHomeView.as_view(), name="vendors"),
    path("admin/", admin.site.urls),
]

urlpatterns += [
    # path("product/<int:pk>/search", views, name="search-product"),
]

templates/pydbapp/base.html
<!DOCTYPE html>
<html>
 
<head>
    <title>AutoComplete</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js">
    </script>
 
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css" rel="stylesheet"
        type="text/css" />
</head>
 
<body>
 {% block content %}
    <input type="text" id="tags">
    <script>
        $(function () {
            var availableTags = [
                {% for product in products %}
            "{{product.name}}"
            {% endfor %}
    ];
        $("#tags").autocomplete({
            source: availableTags
        });
  } );
    </script>

{% endblock %}
</body>
 
</html>

templates/pydbapp/index.html
<h2>Dynamic Content</h2>

<p>The database has the following record counts:</p>
<ul>
  <li><strong>Products:</strong> {{ num_products }}</li>
  <li><strong>Vendors:</strong> {{ num_vendors }}</li>
</ul>

<p>
  You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
</p>

templates/pydbapp/product_search_update.html
{% block content %}
  <h1>Product name: {{ product_instance.name }}</h1>
  <h2>Quantity: {{ product_instance.quantity_on_hand }}</h2>

 
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_p }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}


templates/pydbapp/products.html
{% block content %}
    <h2>Products</h2>
    <ul>
        {% for product in products_list %}
            <li>{{ product.name }}, {{ product.ref_id_expiry_date }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/pydbapp/search_products.html
{% extends 'pydbapp/base.html' %}

{% block content %}

    <div>
    {% if searched %}
        You searched for {{ searched }}
        {% else %}
        Search for Product or Vendor...
    {% endif %}
</div>
<form method=POST action="{% url 'pydbapp:search_products' %}">
    {% csrf_token %}
    <input class="search-form" type="search" placeholder="Search Products or Vendors" aria-label="Search" name="searched">
    <br/>
    <button class="btn-search" type="submit">Search

    </button>


</form>

<br/>
{% for product in products %}
    <div class="card">
<div class="card-header">
{{ product }}
</div>
<div class="card-body">
<h5 class="card-title">Product: {{ Product.name }}</h5>
<p class="card-text">
<ul>
<li>Expiry Date: {{ product.expiry_date }}</li>
<li>Reference ID: {{ product.reference_id }}</li>
<li>Vendor: {{ product.vendor.name }}</li>
{% endfor %}
</ul>



</p>
</div>


{% endblock %}

templates/pydbapp/vendors.html
{% block content %}
    <h2>Vendors</h2>
    <ul>
        {% for vendor in vendors_list %}
            <li>{{ vendor.name }}, {{ vendor.id }}</li>
        {% endfor %}
    </ul>
{% endblock %}